source 'https://rubygems.org'

gem 'pg'
gem 'sequel'
gem 'sequel_pg'
gem 'puma'
gem 'roda'
gem 'tilt', '>=2'
gem 'erubis'
gem 'multipart-post'
gem 'rack-unreloader'
gem 'rodauth'
gem 'bcrypt'
gem 'rack_csrf'
gem 'opal', '>= 0.8'
gem 'opal-browser'
gem 'faye-websocket'
